#!/bin/bash

# To keep plugins around
# mkdir -p .eclipse-docker
# -v $(pwd)/.eclipse:/home/developer \

docker stop eclipse
docker rm eclipse

docker run -d \
  -e DISPLAY=$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v $(pwd):/home/developer/app \
  yurifl/eclipse
