#!/bin/bash

# mkdir -p .eclipse-docker

# docker stop eclipse
# docker rm eclipse

  # -v $(pwd)/.eclipse-docker:/home/developer \
docker run --rm -it \
  -e DISPLAY=$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v $(pwd):/home/developer/app \
  yurifl/eclipse
